# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import person_pb2 as person__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='person.service.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\n\033com.example.tutorial.protosB\rPersonServiceP\001Z\t./go/grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14person.service.proto\x12\x04grpc\x1a\x0cperson.proto\"+\n\x0bSaveRequest\x12\x1c\n\x06person\x18\x01 \x01(\x0b\x32\x0c.grpc.Person\"\x0e\n\x0cSaveResponse\"\r\n\x0bListRequest\",\n\x0cListResponse\x12\x1c\n\x06person\x18\x01 \x03(\x0b\x32\x0c.grpc.Person2y\n\rPersonService\x12/\n\x04Save\x12\x11.grpc.SaveRequest\x1a\x12.grpc.SaveResponse\"\x00\x12\x37\n\nListStream\x12\x11.grpc.ListRequest\x1a\x12.grpc.ListResponse\"\x00\x30\x01\x42\x39\n\x1b\x63om.example.tutorial.protosB\rPersonServiceP\x01Z\t./go/grpcb\x06proto3'
  ,
  dependencies=[person__pb2.DESCRIPTOR,])




_SAVEREQUEST = _descriptor.Descriptor(
  name='SaveRequest',
  full_name='grpc.SaveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='grpc.SaveRequest.person', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=87,
)


_SAVERESPONSE = _descriptor.Descriptor(
  name='SaveResponse',
  full_name='grpc.SaveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=103,
)


_LISTREQUEST = _descriptor.Descriptor(
  name='ListRequest',
  full_name='grpc.ListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=118,
)


_LISTRESPONSE = _descriptor.Descriptor(
  name='ListResponse',
  full_name='grpc.ListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='person', full_name='grpc.ListResponse.person', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=164,
)

_SAVEREQUEST.fields_by_name['person'].message_type = person__pb2._PERSON
_LISTRESPONSE.fields_by_name['person'].message_type = person__pb2._PERSON
DESCRIPTOR.message_types_by_name['SaveRequest'] = _SAVEREQUEST
DESCRIPTOR.message_types_by_name['SaveResponse'] = _SAVERESPONSE
DESCRIPTOR.message_types_by_name['ListRequest'] = _LISTREQUEST
DESCRIPTOR.message_types_by_name['ListResponse'] = _LISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SaveRequest = _reflection.GeneratedProtocolMessageType('SaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREQUEST,
  '__module__' : 'person.service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.SaveRequest)
  })
_sym_db.RegisterMessage(SaveRequest)

SaveResponse = _reflection.GeneratedProtocolMessageType('SaveResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVERESPONSE,
  '__module__' : 'person.service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.SaveResponse)
  })
_sym_db.RegisterMessage(SaveResponse)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'person.service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'person.service_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)


DESCRIPTOR._options = None

_PERSONSERVICE = _descriptor.ServiceDescriptor(
  name='PersonService',
  full_name='grpc.PersonService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=287,
  methods=[
  _descriptor.MethodDescriptor(
    name='Save',
    full_name='grpc.PersonService.Save',
    index=0,
    containing_service=None,
    input_type=_SAVEREQUEST,
    output_type=_SAVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListStream',
    full_name='grpc.PersonService.ListStream',
    index=1,
    containing_service=None,
    input_type=_LISTREQUEST,
    output_type=_LISTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERSONSERVICE)

DESCRIPTOR.services_by_name['PersonService'] = _PERSONSERVICE

# @@protoc_insertion_point(module_scope)
